# Generated by Django 5.1.14 on 2025-11-10 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TravelAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=120, unique=True)),
                ('user_country', models.CharField(blank=True, max_length=120, null=True)),
                ('user_city', models.CharField(blank=True, max_length=120, null=True)),
                ('user_region', models.CharField(blank=True, max_length=120, null=True)),
                ('user_gender', models.CharField(blank=True, max_length=20, null=True)),
                ('destinations', models.JSONField(blank=True, null=True)),
                ('trip_duration', models.PositiveIntegerField(blank=True, null=True)),
                ('travel_group_type', models.CharField(blank=True, max_length=120, null=True)),
                ('travel_group_size', models.PositiveIntegerField(blank=True, null=True)),
                ('budget_level', models.CharField(blank=True, max_length=50, null=True)),
                ('budget_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('budget_currency', models.CharField(blank=True, max_length=10, null=True)),
                ('culinary_preferences', models.JSONField(blank=True, null=True)),
                ('accommodation_preferences', models.JSONField(blank=True, null=True)),
                ('activity_preferences', models.JSONField(blank=True, null=True)),
                ('step_completed', models.CharField(max_length=120)),
                ('completion_status', models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed'), ('abandoned', 'Abandoned')], default='completed', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['session_id'], name='analytics_t_session_677f81_idx'), models.Index(fields=['completion_status'], name='analytics_t_complet_9f3762_idx'), models.Index(fields=['user_country'], name='analytics_t_user_co_12992f_idx'), models.Index(fields=['created_at'], name='analytics_t_created_3e16b5_idx')],
            },
        ),
    ]
