# Generated by Django 5.1.14 on 2025-11-11 20:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
        ('poi', '0011_touristpointreview'),
    ]

    operations = [
        migrations.CreateModel(
            name='TouristPointAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('views', models.PositiveIntegerField(default=0)),
                ('clicks', models.PositiveIntegerField(default=0)),
                ('bookings', models.PositiveIntegerField(default=0)),
                ('revenue', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('unique_visitors', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tourist_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='poi.touristpoint')),
            ],
            options={
                'db_table': 'tourist_point_analytics',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['tourist_point', '-date'], name='tourist_poi_tourist_8b6619_idx'), models.Index(fields=['date'], name='tourist_poi_date_b443a7_idx')],
                'unique_together': {('tourist_point', 'date')},
            },
        ),
    ]
