# Generated by Django 5.1.14 on 2025-11-22 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_travelanalytics_user_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelanalytics',
            name='ai_generated_itinerary',
            field=models.JSONField(blank=True, help_text="Itinéraire complet généré par l'IA", null=True),
        ),
        migrations.AddField(
            model_name='travelanalytics',
            name='ai_provider_used',
            field=models.CharField(blank=True, help_text='Provider IA utilisé (openai, gemini)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='travelanalytics',
            name='used_ai',
            field=models.BooleanField(default=False, help_text="True si l'IA a été utilisée, False si fallback statique"),
        ),
    ]
