# Generated by Django 5.1.14 on 2025-11-11 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setting_key', models.CharField(max_length=120, unique=True)),
                ('setting_value', models.TextField(blank=True)),
                ('setting_type', models.CharField(choices=[('string', 'String'), ('boolean', 'Boolean'), ('number', 'Number')], default='string', max_length=16)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(default='general', max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['setting_key'],
            },
        ),
    ]
