# Generated by Django 5.1.14 on 2025-11-26 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_code', models.CharField(choices=[('kayak', 'Kayak'), ('amadeus', 'Amadeus'), ('hotelbeds', 'HotelBeds'), ('hotelbeds_activities', 'HotelBeds Activities'), ('hotelbeds_transfers', 'HotelBeds Transfers')], max_length=50, verbose_name='Code du fournisseur')),
                ('provider_name', models.CharField(max_length=100, verbose_name='Nom du fournisseur')),
                ('service_type', models.CharField(choices=[('hotels', 'Hôtels'), ('flights', 'Vols'), ('activities', 'Activités'), ('transfers', 'Transferts'), ('restaurants', 'Restaurants'), ('car_rental', 'Location de voiture')], max_length=50, verbose_name='Type de service')),
                ('is_active', models.BooleanField(default=True, help_text='Cochez pour activer ce fournisseur pour ce service', verbose_name='Actif')),
                ('priority', models.IntegerField(default=1, help_text='Ordre de priorité (1 = haute priorité, les plus petits chiffres sont essayés en premier)', verbose_name='Priorité')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('api_endpoint', models.URLField(blank=True, verbose_name="URL de l'API")),
                ('has_credentials', models.BooleanField(default=False, help_text="Les credentials sont dans les variables d'environnement", verbose_name='Credentials configurés')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': "Fournisseur d'API",
                'verbose_name_plural': "Fournisseurs d'API",
                'ordering': ['service_type', 'priority', 'provider_name'],
                'unique_together': {('provider_code', 'service_type')},
            },
        ),
    ]
