# Generated by Django 5.1.14 on 2025-11-27 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_apiprovider'),
    ]

    operations = [
        migrations.CreateModel(
            name='Widget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('widget_code', models.CharField(help_text='Identifiant unique du widget (ex: kayak_hotel_search)', max_length=100, unique=True, verbose_name='Code du widget')),
                ('widget_name', models.CharField(max_length=200, verbose_name='Nom du widget')),
                ('widget_type', models.CharField(choices=[('booking', 'Widget de réservation'), ('search', 'Widget de recherche'), ('promotion', 'Widget promotionnel'), ('information', 'Widget informatif'), ('partner', 'Widget partenaire'), ('social', 'Widget social'), ('custom', 'Widget personnalisé')], max_length=50, verbose_name='Type de widget')),
                ('placement', models.CharField(choices=[('home', "Page d'accueil"), ('search_results', 'Résultats de recherche'), ('detail_page', 'Page de détail'), ('sidebar', 'Barre latérale'), ('footer', 'Pied de page'), ('header', 'En-tête'), ('floating', 'Flottant'), ('modal', 'Modal/Popup')], help_text='Où afficher le widget sur le site', max_length=50, verbose_name='Emplacement')),
                ('service_type', models.CharField(choices=[('all', 'Tous les services'), ('hotels', 'Hôtels'), ('flights', 'Vols'), ('activities', 'Activités'), ('transfers', 'Transferts'), ('restaurants', 'Restaurants'), ('car_rental', 'Location de voiture')], default='all', help_text='Service de voyage concerné', max_length=50, verbose_name='Type de service')),
                ('is_active', models.BooleanField(default=True, help_text='Cochez pour activer ce widget', verbose_name='Actif')),
                ('priority', models.IntegerField(default=1, help_text="Ordre d'affichage (1 = haute priorité)", verbose_name='Priorité')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('configuration', models.JSONField(blank=True, default=dict, help_text='Configuration JSON du widget (dimensions, couleurs, options, etc.)', verbose_name='Configuration')),
                ('content', models.JSONField(blank=True, default=dict, help_text='Contenu JSON du widget (textes, URLs, images, etc.)', verbose_name='Contenu')),
                ('script_url', models.URLField(blank=True, help_text='URL du script JavaScript du widget (si applicable)', verbose_name='URL du script')),
                ('css_url', models.URLField(blank=True, help_text='URL du fichier CSS du widget (si applicable)', verbose_name='URL du CSS')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Widget',
                'verbose_name_plural': 'Widgets',
                'ordering': ['placement', 'priority', 'widget_name'],
            },
        ),
    ]
