# Generated by Django 5.1.14 on 2025-11-10 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_rename_is_published_story_is_featured_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvertisementSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_type', models.CharField(choices=[('link', 'Lien'), ('upload', 'Upload')], default='link', max_length=16)),
                ('video_url', models.URLField(blank=True)),
                ('is_enabled', models.BooleanField(default=False)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('duration_seconds', models.PositiveIntegerField(default=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
