# Generated by Django 5.1.15 on 2025-12-11 11:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_saveditinerary'),
        ('poi', '0019_remove_dietaryrestriction_description_ar_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='story',
            index=models.Index(fields=['story_type', 'is_public', '-created_at'], name='story_type_public_idx'),
        ),
        migrations.AddIndex(
            model_name='story',
            index=models.Index(fields=['location_name'], name='story_location_idx'),
        ),
        migrations.AddIndex(
            model_name='story',
            index=models.Index(fields=['trip_date'], name='story_trip_date_idx'),
        ),
        migrations.AddIndex(
            model_name='story',
            index=models.Index(fields=['is_featured', '-likes_count'], name='story_featured_likes_idx'),
        ),
        migrations.AddIndex(
            model_name='story',
            index=models.Index(fields=['author', '-created_at'], name='story_author_date_idx'),
        ),
        migrations.AddIndex(
            model_name='story',
            index=models.Index(fields=['is_public', '-likes_count', '-created_at'], name='story_popular_idx'),
        ),
    ]
