# Generated by Django 5.1.15 on 2025-12-11 11:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_story_story_type_public_idx_story_story_location_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoryAIProviderConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('openai', 'OpenAI'), ('gemini', 'Gemini'), ('perplexity', 'Perplexity')], max_length=50, unique=True)),
                ('display_name', models.CharField(max_length=100)),
                ('is_enabled', models.BooleanField(default=False)),
                ('model_name', models.CharField(blank=True, max_length=150)),
                ('temperature', models.DecimalField(decimal_places=2, default=0.7, max_digits=4)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Story AI Provider Configuration',
                'verbose_name_plural': 'Story AI Provider Configurations',
                'ordering': ['display_name'],
            },
        ),
    ]
