# Generated by Django

from django.db import migrations


def seed_story_ai_providers(apps, schema_editor):
    """Create initial AI provider configurations for story generation"""
    StoryAIProviderConfig = apps.get_model('content', 'StoryAIProviderConfig')

    providers_data = [
        {
            'provider': 'openai',
            'display_name': 'OpenAI',
            'is_enabled': False,
            'model_name': 'gpt-4o-mini',
            'temperature': 0.75,
            'metadata': {'description': 'OpenAI GPT models for creative story generation'},
        },
        {
            'provider': 'gemini',
            'display_name': 'Google Gemini',
            'is_enabled': False,
            'model_name': 'gemini-2.5-flash',
            'temperature': 0.75,
            'metadata': {'description': 'Google Gemini models for narrative content'},
        },
        {
            'provider': 'perplexity',
            'display_name': 'Perplexity AI',
            'is_enabled': True,  # Default enabled
            'model_name': 'sonar',
            'temperature': 0.75,
            'metadata': {'description': 'Perplexity Sonar for fact-rich travel stories'},
        },
    ]

    for data in providers_data:
        StoryAIProviderConfig.objects.get_or_create(
            provider=data['provider'],
            defaults=data
        )


def reverse_seed(apps, schema_editor):
    """Remove seeded AI providers"""
    StoryAIProviderConfig = apps.get_model('content', 'StoryAIProviderConfig')
    StoryAIProviderConfig.objects.filter(
        provider__in=['openai', 'gemini', 'perplexity']
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_storyaiproviderconfig'),
    ]

    operations = [
        migrations.RunPython(seed_story_ai_providers, reverse_seed),
    ]
