# Generated by Django 5.1.14 on 2025-11-10 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_userroleassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='behavior_profile',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='segments',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
