# Generated by Django 5.1.14 on 2025-11-10 19:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_adminauditlog_adminsession'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission_type', models.CharField(choices=[('user_management', 'Gestion utilisateurs'), ('partner_management', 'Gestion partenaires'), ('poi_management', 'Gestion POI'), ('system_administration', 'Administration système'), ('analytics_access', 'Accès analytics'), ('content_moderation', 'Modération contenu')], max_length=64)),
                ('can_create', models.BooleanField(default=False)),
                ('can_read', models.BooleanField(default=True)),
                ('can_update', models.BooleanField(default=False)),
                ('can_delete', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_permissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['admin__username', 'permission_type'],
                'unique_together': {('admin', 'permission_type')},
            },
        ),
    ]
