# Generated by Django 5.1.14 on 2025-11-11 11:31

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_adminpermission'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itinerary_id', models.UUIDField(blank=True, null=True)),
                ('activity_id', models.UUIDField(blank=True, null=True)),
                ('type', models.CharField(choices=[('activity_reminder', 'Rappel activité'), ('trip_start', 'Début de voyage'), ('trip_end', 'Fin de voyage'), ('general', 'Général'), ('new_partner', 'Nouveau partenaire'), ('new_poi', 'Nouveau POI')], default='general', max_length=64)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('scheduled_for', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_read', models.BooleanField(default=False)),
                ('is_sent', models.BooleanField(default=False)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-scheduled_for', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_reminders', models.BooleanField(default=True)),
                ('trip_start_reminders', models.BooleanField(default=True)),
                ('trip_end_reminders', models.BooleanField(default=True)),
                ('reminder_hours_before', models.PositiveIntegerField(default=24)),
                ('email_notifications', models.BooleanField(default=True)),
                ('push_notifications', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user_id'],
            },
        ),
    ]
