# Generated by Django 5.1.14 on 2025-11-12 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_email_verification_sent_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='editor_content_approved',
            field=models.BooleanField(default=False, help_text="Indique si l'éditeur a été approuvé pour créer du contenu"),
        ),
        migrations.AddField(
            model_name='user',
            name='editor_revenue_share_percentage',
            field=models.DecimalField(decimal_places=2, default=30.0, help_text='Pourcentage des revenus publicitaires pour les éditeurs (défaut: 30%)', max_digits=5),
        ),
        migrations.AddField(
            model_name='user',
            name='partner_subscription_ends_at',
            field=models.DateTimeField(blank=True, help_text="Date de fin de l'abonnement actuel", null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='partner_tier',
            field=models.CharField(blank=True, choices=[('trial', 'Essai Gratuit'), ('standard', 'Standard'), ('premium', 'Premium')], help_text="Niveau d'abonnement pour les partenaires", max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='partner_trial_ends_at',
            field=models.DateTimeField(blank=True, help_text="Date de fin de la période d'essai gratuite", null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='requires_2fa',
            field=models.BooleanField(default=False, help_text="Exige l'authentification à deux facteurs (obligatoire pour SUPER_ADMIN)"),
        ),
        migrations.AddField(
            model_name='user',
            name='two_factor_enabled',
            field=models.BooleanField(default=False, help_text="Indique si l'authentification à deux facteurs est activée"),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('guest', 'Invité'), ('user', 'Utilisateur'), ('partner', 'Partenaire'), ('editor', 'Éditeur'), ('admin', 'Administrateur'), ('super_admin', 'Super Administrateur')], default='user', max_length=20),
        ),
        migrations.AlterField(
            model_name='userroleassignment',
            name='role',
            field=models.CharField(choices=[('guest', 'Invité'), ('user', 'Utilisateur'), ('partner', 'Partenaire'), ('editor', 'Éditeur'), ('admin', 'Administrateur'), ('super_admin', 'Super Administrateur')], max_length=32),
        ),
    ]
