# Generated by Django 5.1.14 on 2025-11-12 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_user_editor_content_approved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='account_deletion_requested',
            field=models.BooleanField(default=False, verbose_name='Suppression demandée'),
        ),
        migrations.AddField(
            model_name='user',
            name='account_deletion_requested_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de la demande de suppression'),
        ),
        migrations.AddField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(blank=True, help_text="Vérification de l'âge minimum (13 ans RGPD)", null=True, verbose_name='Date de naissance'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_age_verified',
            field=models.BooleanField(default=False, verbose_name='Âge vérifié'),
        ),
        migrations.AddField(
            model_name='user',
            name='marketing_consent',
            field=models.BooleanField(default=False, help_text='Accepte de recevoir des communications marketing', verbose_name='Consentement marketing'),
        ),
        migrations.AddField(
            model_name='user',
            name='marketing_consent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date du consentement marketing'),
        ),
        migrations.AddField(
            model_name='user',
            name='privacy_policy_accepted',
            field=models.BooleanField(default=False, verbose_name='Politique de confidentialité acceptée'),
        ),
        migrations.AddField(
            model_name='user',
            name='privacy_policy_accepted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name="Date d'acceptation de la politique"),
        ),
        migrations.AddField(
            model_name='user',
            name='privacy_policy_version',
            field=models.CharField(blank=True, default='1.0', max_length=10, verbose_name='Version de la politique acceptée'),
        ),
        migrations.AddField(
            model_name='user',
            name='scheduled_deletion_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de suppression programmée'),
        ),
        migrations.AddField(
            model_name='user',
            name='terms_accepted',
            field=models.BooleanField(default=False, help_text="Acceptation des Conditions Générales d'Utilisation", verbose_name='CGU acceptées'),
        ),
        migrations.AddField(
            model_name='user',
            name='terms_accepted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name="Date d'acceptation des CGU"),
        ),
    ]
