# Generated by Django 5.1.14 on 2025-11-13 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_usersession'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='city',
            field=models.CharField(blank=True, max_length=100, verbose_name='Ville'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='country',
            field=models.CharField(blank=True, max_length=100, verbose_name='Pays'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='facebook_url',
            field=models.URLField(blank=True, verbose_name='Facebook'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='favorite_destinations',
            field=models.TextField(blank=True, help_text='Séparées par des virgules', verbose_name='Destinations favorites'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='instagram_url',
            field=models.URLField(blank=True, verbose_name='Instagram'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='linkedin_url',
            field=models.URLField(blank=True, verbose_name='LinkedIn'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='occupation',
            field=models.CharField(blank=True, max_length=100, verbose_name='Profession'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='travel_interests',
            field=models.TextField(blank=True, help_text='Ex: plongée, randonnée, gastronomie', verbose_name="Centres d'intérêt"),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='travel_style',
            field=models.CharField(blank=True, choices=[('adventure', 'Aventure'), ('luxury', 'Luxe'), ('budget', 'Budget'), ('cultural', 'Culturel'), ('relaxation', 'Détente'), ('family', 'Famille'), ('solo', 'Solo'), ('group', 'Groupe')], max_length=50, verbose_name='Style de voyage préféré'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='twitter_url',
            field=models.URLField(blank=True, verbose_name='Twitter'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='website_url',
            field=models.URLField(blank=True, verbose_name='Site web'),
        ),
    ]
