# Generated by Django 5.1.14 on 2025-11-13 22:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_add_extended_profile_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='allow_messages',
            field=models.BooleanField(default=True, verbose_name='Autoriser les messages'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='allow_profile_search',
            field=models.BooleanField(default=True, verbose_name='Visible dans la recherche'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_public',
            field=models.BooleanField(default=True, verbose_name='Profil public'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profile_visibility',
            field=models.CharField(choices=[('public', 'Public'), ('friends_only', 'Amis uniquement'), ('private', 'Privé')], default='public', max_length=20, verbose_name='Visibilité du profil'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='show_bookings',
            field=models.BooleanField(default=False, verbose_name='Afficher mes réservations'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='show_followers',
            field=models.BooleanField(default=True, verbose_name='Afficher mes abonnés'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='show_itineraries',
            field=models.BooleanField(default=True, verbose_name='Afficher mes itinéraires'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='show_stories',
            field=models.BooleanField(default=True, verbose_name='Afficher mes récits'),
        ),
        migrations.CreateModel(
            name='UserFollow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de suivi')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following_relationships', to=settings.AUTH_USER_MODEL, verbose_name='Abonné')),
                ('following', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follower_relationships', to=settings.AUTH_USER_MODEL, verbose_name='Suivi')),
            ],
            options={
                'verbose_name': 'Abonnement',
                'verbose_name_plural': 'Abonnements',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['follower', 'is_active'], name='accounts_us_followe_bfeb90_idx'), models.Index(fields=['following', 'is_active'], name='accounts_us_followi_0de909_idx')],
                'unique_together': {('follower', 'following')},
            },
        ),
    ]
