# Generated by Django 5.1.14 on 2025-11-13 23:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_add_privacy_and_follow_system'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom du badge')),
                ('description', models.TextField(verbose_name='Description')),
                ('icon', models.CharField(choices=[('book', 'Livre'), ('trophy', 'Trophée'), ('plane', 'Avion'), ('star', 'Étoile'), ('heart', 'Coeur'), ('map', 'Carte'), ('camera', 'Caméra'), ('globe', 'Globe'), ('compass', 'Boussole'), ('medal', 'Médaille')], default='trophy', max_length=20, verbose_name='Icône')),
                ('criteria_type', models.CharField(choices=[('story_count', 'Nombre de récits'), ('like_count', 'Nombre de likes reçus'), ('booking_count', 'Nombre de réservations'), ('itinerary_count', "Nombre d'itinéraires"), ('follower_count', "Nombre d'abonnés"), ('following_count', "Nombre d'abonnements"), ('view_count', 'Nombre de vues'), ('comment_count', 'Nombre de commentaires'), ('share_count', 'Nombre de partages')], max_length=30, verbose_name='Type de critère')),
                ('criteria_value', models.IntegerField(verbose_name='Valeur seuil')),
                ('is_active', models.BooleanField(default=True, verbose_name='Badge actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Badge',
                'verbose_name_plural': 'Badges',
                'ordering': ['criteria_value', 'name'],
                'indexes': [models.Index(fields=['criteria_type', 'criteria_value'], name='accounts_ac_criteri_8ef2d2_idx'), models.Index(fields=['is_active'], name='accounts_ac_is_acti_93f050_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earned', models.BooleanField(default=False, verbose_name='Badge débloqué')),
                ('earned_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de déblocage')),
                ('progress', models.IntegerField(default=0, verbose_name='Progression actuelle')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_achievements', to='accounts.achievement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Badge utilisateur',
                'verbose_name_plural': 'Badges utilisateurs',
                'ordering': ['-earned', '-earned_at', 'achievement__criteria_value'],
                'indexes': [models.Index(fields=['user', 'earned'], name='accounts_us_user_id_69d975_idx'), models.Index(fields=['earned_at'], name='accounts_us_earned__18317c_idx')],
                'unique_together': {('user', 'achievement')},
            },
        ),
    ]
