# Generated by Django 5.1.14 on 2025-11-10 15:17

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
        ('partners', '0001_initial'),
        ('poi', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerCommission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('commission_rate', models.DecimalField(decimal_places=2, default=Decimal('15.0'), max_digits=5)),
                ('booking_reference', models.CharField(blank=True, max_length=64)),
                ('customer_name', models.CharField(blank=True, max_length=255)),
                ('booking_date', models.DateField()),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('paid', 'Paid'), ('failed', 'Failed')], default='pending', max_length=32)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partner_commissions', to='bookings.booking')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partner_commissions', to=settings.AUTH_USER_MODEL)),
                ('tourist_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partner_commissions', to='poi.touristpoint')),
            ],
            options={
                'ordering': ['-booking_date'],
            },
        ),
        migrations.CreateModel(
            name='PartnerEndpointHealth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint_url', models.URLField()),
                ('status', models.CharField(choices=[('healthy', 'Healthy'), ('degraded', 'Degraded'), ('unhealthy', 'Unhealthy')], default='healthy', max_length=32)),
                ('response_time_ms', models.PositiveIntegerField(default=0)),
                ('uptime_percentage', models.DecimalField(decimal_places=2, default=100.0, max_digits=5)),
                ('success_rate_24h', models.DecimalField(decimal_places=2, default=100.0, max_digits=5)),
                ('last_checked', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='endpoint_health', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='PartnerPaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method_type', models.CharField(choices=[('bank', 'Bank transfer'), ('paypal', 'PayPal'), ('stripe', 'Stripe')], max_length=32)),
                ('label', models.CharField(blank=True, max_length=255)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_methods', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_default', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='PartnerWithdrawal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=32)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partner_withdrawals', to=settings.AUTH_USER_MODEL)),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='withdrawals', to='partners.partnerpaymentmethod')),
            ],
            options={
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='PartnerBookingConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_type', models.CharField(choices=[('internal', 'Internal'), ('external', 'External'), ('api', 'API'), ('webhook', 'Webhook')], default='external', max_length=32)),
                ('endpoint_url', models.URLField(blank=True)),
                ('webhook_url', models.URLField(blank=True)),
                ('api_credentials', models.JSONField(blank=True, default=dict)),
                ('custom_fields', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=False)),
                ('test_mode', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_configs', to=settings.AUTH_USER_MODEL)),
                ('tourist_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_configs', to='poi.touristpoint')),
            ],
            options={
                'ordering': ['-updated_at'],
                'unique_together': {('partner', 'tourist_point')},
            },
        ),
    ]
