# Generated by Django 5.1.15 on 2026-06-21 09:34

import apps.partners.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0003_commission_rate_invoice'),
        ('poi', '0026_translationcache'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerprofile',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='partnerprofile',
            name='business_category',
            field=models.CharField(blank=True, choices=[('accommodation', 'Hébergement'), ('restaurant', 'Restaurant'), ('cafe', 'Café'), ('bar', 'Bar'), ('activity', 'Activité / Loisir'), ('museum', 'Musée / Culture'), ('shop', 'Boutique'), ('transport', 'Transport'), ('service', 'Service'), ('other', 'Autre')], max_length=32),
        ),
        migrations.AddField(
            model_name='partnerprofile',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partner_profiles', to='poi.city'),
        ),
        migrations.AddField(
            model_name='partnerprofile',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='partnerprofile',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partner_profiles', to='poi.country'),
        ),
        migrations.AddField(
            model_name='partnerprofile',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='partnerprofile',
            name='postal_code',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='partnerprofile',
            name='company_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='partnerprofile',
            name='status',
            field=models.CharField(choices=[('draft', 'Brouillon'), ('pending', 'En attente'), ('approved', 'Approuvé'), ('rejected', 'Refusé'), ('suspended', 'Suspendu')], default='draft', max_length=32),
        ),
        migrations.CreateModel(
            name='PartnerKYC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legal_name', models.CharField(blank=True, max_length=255)),
                ('legal_form', models.CharField(blank=True, max_length=120)),
                ('registration_number', models.CharField(blank=True, max_length=120)),
                ('vat_number', models.CharField(blank=True, max_length=120)),
                ('tax_id', models.CharField(blank=True, max_length=120)),
                ('registered_address', models.CharField(blank=True, max_length=255)),
                ('rep_full_name', models.CharField(blank=True, max_length=255)),
                ('rep_date_of_birth', models.DateField(blank=True, null=True)),
                ('rep_nationality', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(choices=[('not_submitted', 'Non soumis'), ('pending', 'En attente de vérification'), ('verified', 'Vérifié'), ('rejected', 'Refusé')], default='not_submitted', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kyc', to='partners.partnerprofile')),
                ('registration_country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partner_kycs', to='poi.country')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_kycs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PartnerKYCDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('business_registration', 'Extrait de registre / immatriculation'), ('representative_id', "Pièce d'identité du représentant"), ('bank_rib', 'RIB / coordonnées bancaires'), ('proof_of_address', 'Justificatif de domicile')], max_length=40)),
                ('file', models.FileField(upload_to=apps.partners.models.kyc_document_upload_path)),
                ('original_name', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('kyc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='partners.partnerkyc')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
