# Generated by Django 5.1.14 on 2025-11-10 08:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=32, unique=True)),
                ('label_fr', models.CharField(max_length=120)),
                ('label_en', models.CharField(blank=True, max_length=120)),
                ('min_daily_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('max_daily_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('default_daily_amount', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('description_fr', models.TextField(blank=True)),
                ('description_en', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DifficultyLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=32, unique=True)),
                ('label_fr', models.CharField(max_length=120)),
                ('label_en', models.CharField(blank=True, max_length=120)),
                ('level_value', models.PositiveSmallIntegerField(default=1)),
                ('is_child_friendly', models.BooleanField(default=True)),
                ('is_senior_friendly', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=64, unique=True)),
                ('label_fr', models.CharField(max_length=255)),
                ('label_en', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TouristPoint',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=64)),
                ('website_url', models.URLField(blank=True)),
                ('price_range', models.CharField(blank=True, max_length=64)),
                ('rating', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('review_count', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('is_restaurant', models.BooleanField(default=False)),
                ('is_accommodation', models.BooleanField(default=False)),
                ('is_activity', models.BooleanField(default=False)),
                ('amenities', models.JSONField(blank=True, default=list)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('budget_level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='poi.budgetlevel')),
                ('difficulty_level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='poi.difficultylevel')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tourist_points', to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(blank=True, related_name='tourist_points', to='poi.tag')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='POIMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(default='image', max_length=32)),
                ('file', models.FileField(blank=True, upload_to='poi-media/')),
                ('external_url', models.URLField(blank=True)),
                ('alt_text', models.CharField(blank=True, max_length=255)),
                ('tourist_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='poi.touristpoint')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
