# Generated by Django 5.1.14 on 2025-11-10 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='touristpoint',
            name='backend',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='touristpoint',
            name='blocked_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='touristpoint',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='touristpoint',
            name='rejection_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='touristpoint',
            name='status',
            field=models.CharField(choices=[('draft', 'Brouillon'), ('pending_validation', 'En attente'), ('under_review', 'En cours de revue'), ('approved', 'Approuvé'), ('rejected', 'Rejeté'), ('blocked', 'Bloqué')], default='pending_validation', max_length=32),
        ),
        migrations.AddField(
            model_name='touristpoint',
            name='submission_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='touristpoint',
            name='validation_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
