# Generated by Django 5.1.14 on 2025-11-10 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poi', '0003_poiconversation_poiconversationmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetCurrency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=16, unique=True)),
                ('name_fr', models.CharField(max_length=120)),
                ('name_en', models.CharField(blank=True, max_length=120)),
                ('symbol', models.CharField(default='€', max_length=8)),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['display_order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='BudgetFlexibilityOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=32, unique=True)),
                ('label_fr', models.CharField(max_length=120)),
                ('label_en', models.CharField(blank=True, max_length=120)),
                ('description_fr', models.TextField(blank=True)),
                ('description_en', models.TextField(blank=True)),
                ('percentage_variation', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['display_order', 'code'],
            },
        ),
        migrations.AddField(
            model_name='budgetlevel',
            name='display_order',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='budgetlevel',
            name='icon_emoji',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AddField(
            model_name='budgetlevel',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
