# Generated by Django 5.1.14 on 2025-11-10 20:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poi', '0005_country_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityCategory',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=64, unique=True)),
                ('label_fr', models.CharField(max_length=255)),
                ('label_en', models.CharField(blank=True, max_length=255)),
                ('description_fr', models.TextField(blank=True)),
                ('description_en', models.TextField(blank=True)),
                ('icon_emoji', models.CharField(blank=True, max_length=8)),
                ('icon_name', models.CharField(blank=True, max_length=64)),
                ('color_class', models.CharField(blank=True, max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['display_order', 'label_fr'],
            },
        ),
        migrations.CreateModel(
            name='ActivityIntensityLevel',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=64, unique=True)),
                ('label_fr', models.CharField(max_length=255)),
                ('label_en', models.CharField(blank=True, max_length=255)),
                ('description_fr', models.TextField(blank=True)),
                ('description_en', models.TextField(blank=True)),
                ('icon_emoji', models.CharField(blank=True, max_length=8)),
                ('level_value', models.PositiveSmallIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['display_order', 'level_value'],
            },
        ),
        migrations.CreateModel(
            name='ActivityAvoidance',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=64, unique=True)),
                ('label_fr', models.CharField(max_length=255)),
                ('label_en', models.CharField(blank=True, max_length=255)),
                ('description_fr', models.TextField(blank=True)),
                ('description_en', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='avoidances', to='poi.activitycategory')),
            ],
            options={
                'ordering': ['display_order', 'label_fr'],
            },
        ),
        migrations.CreateModel(
            name='ActivityInterest',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=64, unique=True)),
                ('label_fr', models.CharField(max_length=255)),
                ('label_en', models.CharField(blank=True, max_length=255)),
                ('description_fr', models.TextField(blank=True)),
                ('description_en', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interests', to='poi.activitycategory')),
            ],
            options={
                'ordering': ['display_order', 'label_fr'],
            },
        ),
    ]
