# Generated by Django 5.1.14 on 2025-11-10 20:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poi', '0006_activitycategory_activityintensitylevel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CuisineType',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=64, unique=True)),
                ('label_fr', models.CharField(max_length=255)),
                ('label_en', models.CharField(blank=True, max_length=255)),
                ('description_fr', models.TextField(blank=True)),
                ('description_en', models.TextField(blank=True)),
                ('region', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['display_order', 'label_fr'],
            },
        ),
        migrations.CreateModel(
            name='CulinaryAdventureLevel',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=64, unique=True)),
                ('label_fr', models.CharField(max_length=255)),
                ('label_en', models.CharField(blank=True, max_length=255)),
                ('description_fr', models.TextField(blank=True)),
                ('description_en', models.TextField(blank=True)),
                ('level_value', models.PositiveSmallIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['display_order', 'level_value'],
            },
        ),
        migrations.CreateModel(
            name='DietaryRestriction',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=64, unique=True)),
                ('label_fr', models.CharField(max_length=255)),
                ('label_en', models.CharField(blank=True, max_length=255)),
                ('description_fr', models.TextField(blank=True)),
                ('description_en', models.TextField(blank=True)),
                ('icon_emoji', models.CharField(blank=True, max_length=8)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['display_order', 'label_fr'],
            },
        ),
        migrations.CreateModel(
            name='RestaurantCategory',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=64, unique=True)),
                ('label_fr', models.CharField(max_length=255)),
                ('label_en', models.CharField(blank=True, max_length=255)),
                ('description_fr', models.TextField(blank=True)),
                ('description_en', models.TextField(blank=True)),
                ('icon_emoji', models.CharField(blank=True, max_length=8)),
                ('price_range_min', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('price_range_max', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['display_order', 'label_fr'],
            },
        ),
    ]
