# Generated by Django 5.1.14 on 2025-11-10 20:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poi', '0007_cuisinetype_culinaryadventurelevel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TravelGroupType',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=64, unique=True)),
                ('label_fr', models.CharField(max_length=255)),
                ('label_en', models.CharField(blank=True, max_length=255)),
                ('description_fr', models.TextField(blank=True)),
                ('description_en', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, max_length=64)),
                ('color', models.CharField(blank=True, max_length=32)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['display_order', 'label_fr'],
            },
        ),
        migrations.CreateModel(
            name='TravelGroupConfiguration',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('has_fixed_size', models.BooleanField(default=False)),
                ('fixed_size', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('min_size', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('max_size', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('default_size', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('allows_children', models.BooleanField(default=True)),
                ('min_child_age', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('max_child_age', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('requires_size_input', models.BooleanField(default=True)),
                ('travel_group_type', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='configuration', to='poi.travelgrouptype')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TravelGroupSubtype',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=64)),
                ('label_fr', models.CharField(max_length=255)),
                ('label_en', models.CharField(blank=True, max_length=255)),
                ('description_fr', models.TextField(blank=True)),
                ('description_en', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('travel_group_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtypes', to='poi.travelgrouptype')),
            ],
            options={
                'ordering': ['display_order', 'label_fr'],
                'unique_together': {('travel_group_type', 'code')},
            },
        ),
    ]
