# Generated by Django 5.1.14 on 2025-11-11 05:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poi', '0008_travelgrouptype_travelgroupconfiguration_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccommodationAccessibilityFeature',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=64, unique=True)),
                ('label_fr', models.CharField(max_length=255)),
                ('label_en', models.CharField(blank=True, max_length=255)),
                ('description_fr', models.TextField(blank=True)),
                ('description_en', models.TextField(blank=True)),
                ('icon_emoji', models.CharField(blank=True, max_length=8)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['display_order', 'label_fr'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AccommodationAmbiance',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=64, unique=True)),
                ('label_fr', models.CharField(max_length=255)),
                ('label_en', models.CharField(blank=True, max_length=255)),
                ('description_fr', models.TextField(blank=True)),
                ('description_en', models.TextField(blank=True)),
                ('icon_emoji', models.CharField(blank=True, max_length=8)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['display_order', 'label_fr'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AccommodationAmenity',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=64, unique=True)),
                ('label_fr', models.CharField(max_length=255)),
                ('label_en', models.CharField(blank=True, max_length=255)),
                ('description_fr', models.TextField(blank=True)),
                ('description_en', models.TextField(blank=True)),
                ('icon_emoji', models.CharField(blank=True, max_length=8)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('category', models.CharField(blank=True, max_length=120)),
            ],
            options={
                'ordering': ['display_order', 'label_fr'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AccommodationLocation',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=64, unique=True)),
                ('label_fr', models.CharField(max_length=255)),
                ('label_en', models.CharField(blank=True, max_length=255)),
                ('description_fr', models.TextField(blank=True)),
                ('description_en', models.TextField(blank=True)),
                ('icon_emoji', models.CharField(blank=True, max_length=8)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['display_order', 'label_fr'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AccommodationSecurityFeature',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=64, unique=True)),
                ('label_fr', models.CharField(max_length=255)),
                ('label_en', models.CharField(blank=True, max_length=255)),
                ('description_fr', models.TextField(blank=True)),
                ('description_en', models.TextField(blank=True)),
                ('icon_emoji', models.CharField(blank=True, max_length=8)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['display_order', 'label_fr'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AccommodationType',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=64, unique=True)),
                ('label_fr', models.CharField(max_length=255)),
                ('label_en', models.CharField(blank=True, max_length=255)),
                ('description_fr', models.TextField(blank=True)),
                ('description_en', models.TextField(blank=True)),
                ('icon_emoji', models.CharField(blank=True, max_length=8)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['display_order', 'label_fr'],
                'abstract': False,
            },
        ),
    ]
