# Generated by Django 5.1.14 on 2025-11-11 14:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poi', '0010_favoritetouristpoint'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TouristPointReview',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rating', models.PositiveSmallIntegerField(default=5, help_text='Rating from 1 to 5')),
                ('comment', models.TextField()),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tourist_point_reviews', to=settings.AUTH_USER_MODEL)),
                ('tourist_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='poi.touristpoint')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tourist_point', '-created_at'], name='poi_tourist_tourist_801c12_idx'), models.Index(fields=['reviewer', '-created_at'], name='poi_tourist_reviewe_9550fd_idx')],
                'unique_together': {('tourist_point', 'reviewer')},
            },
        ),
    ]
