# Generated by Django 5.1.14 on 2025-11-22 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poi', '0018_activity_multilingual_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dietaryrestriction',
            name='description_ar',
        ),
        migrations.RemoveField(
            model_name='dietaryrestriction',
            name='description_hi',
        ),
        migrations.RemoveField(
            model_name='dietaryrestriction',
            name='description_it',
        ),
        migrations.RemoveField(
            model_name='dietaryrestriction',
            name='description_ja',
        ),
        migrations.RemoveField(
            model_name='dietaryrestriction',
            name='description_pt',
        ),
        migrations.RemoveField(
            model_name='dietaryrestriction',
            name='description_ru',
        ),
        migrations.RemoveField(
            model_name='dietaryrestriction',
            name='description_zh',
        ),
    ]
