# Generated by Django 5.1.15 — ajout du champ icon_name (icône SVG lucide) + backfill

from django.db import migrations, models

# Mapping code de taxonomie -> nom d'icône lucide (miroir de frontend/src/lib/taxonomyIcon.tsx)
CODE_ICONS = {
    "accessible_parking": "Accessibility", "adapted_bathroom": "Bath", "elevator": "MoveVertical",
    "hearing_loop": "Ear", "visual_signage": "Signpost", "wheelchair_access": "Accessibility",
    "business": "Briefcase", "eco_friendly": "Leaf", "family_friendly": "Users", "luxury": "Gem",
    "party": "PartyPopper", "pet_friendly": "PawPrint", "quiet_relaxing": "Smile", "romantic": "Heart",
    "ac": "Snowflake", "breakfast": "Croissant", "family_rooms": "Users", "gym": "Dumbbell",
    "kitchen": "CookingPot", "laundry": "WashingMachine", "non_smoking": "CigaretteOff",
    "parking": "SquareParking", "pets_allowed": "PawPrint", "pool": "Waves", "spa": "Flower2", "wifi": "Wifi",
    "beach_front": "Umbrella", "city_center": "Building2", "countryside": "Trees", "historic_center": "Landmark",
    "near_airport": "Plane", "near_poi": "MapPin", "near_public_transport": "TrainFront", "quiet_neighbourhood": "VolumeX",
    "24_7_reception": "Clock", "neighborhood_safety": "ShieldCheck", "safe_deposit": "Lock",
    "secure_luggage_storage": "Luggage", "security_cameras": "Cctv", "smoke_detectors": "Siren",
    "apartment": "Building", "bnb": "ConciergeBell", "camping": "Tent", "guesthouse": "Home",
    "hostel": "BedDouble", "hotel": "Hotel", "resort": "Palmtree", "serviced_apartment": "BriefcaseBusiness",
    "adventure": "Mountain", "beach": "Waves", "culture": "Drama", "family": "Users",
    "gastronomy": "UtensilsCrossed", "nature": "TreePine", "nightlife": "Martini", "photography": "Camera",
    "shopping": "ShoppingBag", "sports": "Trophy", "wellness": "Flower",
    "active": "Activity", "intense": "Zap", "moderate": "Footprints", "relaxed": "Coffee",
    "egg_free": "EggOff", "gluten_free": "WheatOff", "halal": "Moon", "kosher": "Star",
    "lactose_free": "MilkOff", "nut_free": "NutOff", "pescatarian": "Fish", "shellfish_free": "FishOff",
    "vegan": "Sprout", "vegetarian": "Salad",
    "bakery": "Croissant", "bistro": "Beer", "cafe": "Coffee", "fine_dining": "ChefHat",
    "food_truck": "Truck", "market_stall": "Store", "restaurant": "Utensils", "vegan_friendly": "Leaf", "wine_bar": "Wine",
    "budget": "PiggyBank", "economy": "PiggyBank", "low": "PiggyBank", "standard": "Wallet",
    "mid": "Wallet", "comfort": "Wallet", "premium": "Gem", "luxe": "Gem", "high": "Gem",
}

_MODELS = [
    "BudgetLevel", "ActivityIntensityLevel", "AccommodationType", "AccommodationAmenity",
    "AccommodationLocation", "AccommodationAccessibilityFeature", "AccommodationSecurityFeature",
    "AccommodationAmbiance", "DietaryRestriction", "RestaurantCategory",
]


def backfill_icon_name(apps, schema_editor):
    """Remplit icon_name depuis le code de chaque entrée (best-effort)."""
    for model_name in _MODELS:
        Model = apps.get_model("poi", model_name)
        for obj in Model.objects.all():
            if getattr(obj, "icon_name", ""):
                continue
            code = (getattr(obj, "code", "") or "").strip()
            lucide = CODE_ICONS.get(code)
            if lucide:
                obj.icon_name = lucide
                obj.save(update_fields=["icon_name"])


class Migration(migrations.Migration):

    dependencies = [
        ('poi', '0019_remove_dietaryrestriction_description_ar_and_more'),
    ]

    operations = [
        migrations.AddField(model_name='accommodationaccessibilityfeature', name='icon_name', field=models.CharField(blank=True, default='', max_length=64)),
        migrations.AddField(model_name='accommodationambiance', name='icon_name', field=models.CharField(blank=True, default='', max_length=64)),
        migrations.AddField(model_name='accommodationamenity', name='icon_name', field=models.CharField(blank=True, default='', max_length=64)),
        migrations.AddField(model_name='accommodationlocation', name='icon_name', field=models.CharField(blank=True, default='', max_length=64)),
        migrations.AddField(model_name='accommodationsecurityfeature', name='icon_name', field=models.CharField(blank=True, default='', max_length=64)),
        migrations.AddField(model_name='accommodationtype', name='icon_name', field=models.CharField(blank=True, default='', max_length=64)),
        migrations.AddField(model_name='activityintensitylevel', name='icon_name', field=models.CharField(blank=True, default='', max_length=64)),
        migrations.AddField(model_name='budgetlevel', name='icon_name', field=models.CharField(blank=True, default='', max_length=64)),
        migrations.AddField(model_name='dietaryrestriction', name='icon_name', field=models.CharField(blank=True, default='', max_length=64)),
        migrations.AddField(model_name='restaurantcategory', name='icon_name', field=models.CharField(blank=True, default='', max_length=64)),
        migrations.RunPython(backfill_icon_name, migrations.RunPython.noop),
    ]
